const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=UTF-8'}});
const id=()=>crypto.randomUUID();
function cookies(request){return Object.fromEntries((request.headers.get('cookie')||'').split(';').filter(Boolean).map(item=>{const i=item.indexOf('=');return[item.slice(0,i).trim(),decodeURIComponent(item.slice(i+1))]}))}
function setCookie(name,value,maxAge,secure=true){return `${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${secure?'; Secure':''}`}
function safeReturnTo(value){return typeof value==='string'&&value.startsWith('/')&&!value.startsWith('//')?value:'/'}
async function secretEqual(left,right){
  const encoder=new TextEncoder(),[leftHash,rightHash]=await Promise.all([crypto.subtle.digest('SHA-256',encoder.encode(String(left))),crypto.subtle.digest('SHA-256',encoder.encode(String(right)))]),leftBytes=new Uint8Array(leftHash),rightBytes=new Uint8Array(rightHash);let difference=0;
  for(let index=0;index<leftBytes.length;index++)difference|=leftBytes[index]^rightBytes[index];
  return difference===0;
}
async function userFor(request,env){const session=cookies(request).split_circle_session;if(!session||!env.DB)return null;return env.DB.prepare(`SELECT u.*,p.id AS person_id,p.public_id FROM sessions s JOIN users u ON u.id=s.user_id JOIN people p ON p.user_id=u.id WHERE s.id=? AND s.expires_at>CURRENT_TIMESTAMP`).bind(session).first()}
async function requireUser(request,env){const user=await userFor(request,env);if(!user)throw new Response('Sign in required',{status:401});return user}
function requireDb(env){if(!env.DB)throw new Response('D1 is not configured yet.',{status:503})}

async function callback(request,env,url){
  const jar=cookies(request),state=url.searchParams.get('state');
  if(!state||!jar.split_circle_oauth_state||state!==jar.split_circle_oauth_state)return new Response('OAuth state did not match.',{status:400});
  const code=url.searchParams.get('code');if(!code)return new Response('Google sign-in was cancelled.',{status:400});
  const redirectUri=`${url.origin}/auth/callback`,form=new URLSearchParams({code,client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,redirect_uri:redirectUri,grant_type:'authorization_code'});
  const token=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:form}).then(r=>r.ok?r.json():Promise.reject(new Error('Google token exchange failed')));
  const profile=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{authorization:`Bearer ${token.access_token}`}}).then(r=>r.ok?r.json():Promise.reject(new Error('Google profile lookup failed')));
  const existing=await env.DB.prepare('SELECT id FROM users WHERE google_sub=?').bind(profile.sub).first(),userId=existing?.id||id();
  await env.DB.prepare(`INSERT INTO users(id,google_sub,email,display_name,avatar_url) VALUES(?,?,?,?,?) ON CONFLICT(google_sub) DO UPDATE SET email=excluded.email,display_name=excluded.display_name,avatar_url=excluded.avatar_url`).bind(userId,profile.sub,profile.email,profile.name||profile.email,profile.picture||null).run();
  const person=await env.DB.prepare('SELECT id FROM people WHERE user_id=?').bind(userId).first();
  if(!person)await env.DB.prepare('INSERT INTO people(id,public_id,display_name,user_id) VALUES(?,?,?,?)').bind(id(),`#${id().replaceAll('-','').slice(0,8)}`,profile.name||profile.email,userId).run();
  else await env.DB.prepare('UPDATE people SET display_name=? WHERE id=?').bind(profile.name||profile.email,person.id).run();
  const session=id(),expiry=new Date(Date.now()+30*864e5).toISOString();await env.DB.prepare('INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)').bind(session,userId,expiry).run();
  const secure=url.protocol==='https:',headers=new Headers({location:safeReturnTo(jar.split_circle_return_to)});headers.append('set-cookie',setCookie('split_circle_session',session,30*86400,secure));headers.append('set-cookie',setCookie('split_circle_oauth_state','',0,secure));headers.append('set-cookie',setCookie('split_circle_return_to','',0,secure));return new Response(null,{status:302,headers});
}
async function groupForUser(env,groupId,user){return env.DB.prepare(`SELECT g.* FROM groups g JOIN group_members gm ON gm.group_id=g.id WHERE g.id=? AND gm.person_id=?`).bind(groupId,user.person_id).first()}
function cleanFormula(value,totalCents,memberIds){
  if(!value||!Array.isArray(value.questions)||!Array.isArray(value.components))throw new Error('A formula split needs questions and components.');
  const key=value=>typeof value==='string'&&/^[a-zA-Z][a-zA-Z0-9_-]{0,39}$/.test(value),questions=value.questions.map(question=>({id:question.id,label:String(question.label||'').trim().slice(0,100),options:Array.isArray(question.options)?question.options.map(option=>({id:option.id,label:String(option.label||'').trim().slice(0,80)})):[]}));
  if(!questions.length||questions.some(question=>!key(question.id)||!question.label||question.options.length<2||question.options.some(option=>!key(option.id)||!option.label)||new Set(question.options.map(option=>option.id)).size!==question.options.length)||new Set(questions.map(question=>question.id)).size!==questions.length)throw new Error('Formula questions need unique IDs, labels, and at least two valid options.');
  const questionMap=new Map(questions.map(question=>[question.id,question])),components=value.components.map(component=>{const cents=Math.round(Number(component.amount)*100),eligibility=component.eligibility&&{questionId:component.eligibility.questionId,optionIds:Array.isArray(component.eligibility.optionIds)?component.eligibility.optionIds:[]};if(!key(component.id)||!String(component.label||'').trim()||!Number.isSafeInteger(cents)||cents<0)throw new Error('Every formula component needs a valid ID, label, and non-negative amount.');if(eligibility){const question=questionMap.get(eligibility.questionId);if(!question||!eligibility.optionIds.length||eligibility.optionIds.some(optionId=>!question.options.some(option=>option.id===optionId)))throw new Error('Formula component eligibility must refer to a declared question option.')}return{id:component.id,label:String(component.label).trim().slice(0,100),amount:cents/100,...(eligibility?{eligibility}:{})}});
  if(!components.length||new Set(components.map(component=>component.id)).size!==components.length||components.reduce((sum,component)=>sum+Math.round(component.amount*100),0)!==totalCents)throw new Error('Formula component amounts must equal the split total exactly.');
  return{questions,components,memberIds};
}
function calculateFormulaShares(formula,answers,totalCents){
  const byPerson=Object.fromEntries(formula.memberIds.map(personId=>[personId,{}]));for(const answer of answers)if(byPerson[answer.person_id])byPerson[answer.person_id][answer.question_id]=answer.option_id;
  const complete=formula.memberIds.every(personId=>formula.questions.every(question=>question.id in byPerson[personId]));if(!complete)return{complete:false,shares:formula.memberIds.map(personId=>({personId,cents:0}))};
  const totals=Object.fromEntries(formula.memberIds.map(personId=>[personId,0]));for(const component of formula.components){const cents=Math.round(component.amount*100);if(cents===0)continue;const eligible=formula.memberIds.filter(personId=>!component.eligibility||component.eligibility.optionIds.includes(byPerson[personId][component.eligibility.questionId]));if(!eligible.length)return{complete:false,shares:formula.memberIds.map(personId=>({personId,cents:0})),reason:'No one matches '+component.label+'.'};const base=Math.floor(cents/eligible.length),remainder=cents%eligible.length;eligible.forEach((personId,index)=>totals[personId]+=base+(index<remainder?1:0))}const shares=formula.memberIds.map(personId=>({personId,cents:totals[personId]}));return{complete:shares.reduce((sum,share)=>sum+share.cents,0)===totalCents,shares};
}
async function serializeGroups(env,user){
  const rows=await env.DB.prepare(`SELECT g.* FROM groups g JOIN group_members gm ON gm.group_id=g.id WHERE gm.person_id=? ORDER BY g.created_at DESC`).bind(user.person_id).all(),output=[];
  for(const group of rows.results){
    const people=await env.DB.prepare(`SELECT p.id,p.public_id,p.display_name,p.user_id FROM people p JOIN group_members gm ON gm.person_id=p.id WHERE gm.group_id=? ORDER BY p.created_at`).bind(group.id).all();
    const memberRecords=people.results.map(p=>({id:p.id,publicId:p.public_id,displayName:p.display_name,claimed:Boolean(p.user_id),isCurrentUser:p.id===user.person_id}));
    const uiName=personId=>personId===user.person_id?'You':memberRecords.find(p=>p.id===personId)?.displayName||'Unknown member';
    const expenseRows=await env.DB.prepare(`SELECT id,title,total_cents,payer_person_id,split_method,comment,formula_json,created_at FROM expenses WHERE group_id=? ORDER BY created_at DESC`).bind(group.id).all(),expenses=[];
    for(const expense of expenseRows.results){
      const shareRows=await env.DB.prepare('SELECT person_id,amount_cents FROM expense_shares WHERE expense_id=?').bind(expense.id).all(),formula=expense.formula_json?JSON.parse(expense.formula_json):null,answerRows=formula?await env.DB.prepare('SELECT person_id,question_id,option_id FROM expense_answers WHERE expense_id=?').bind(expense.id).all():{results:[]},calculated=formula?calculateFormulaShares(formula,answerRows.results,expense.total_cents):null;
      const myAnswers=Object.fromEntries(answerRows.results.filter(answer=>answer.person_id===user.person_id).map(answer=>[answer.question_id,answer.option_id]));
      const answerCountsByQuestion=formula?Object.fromEntries(formula.questions.map(question=>[question.id,Object.fromEntries(question.options.map(option=>[option.id,answerRows.results.filter(answer=>answer.question_id===question.id&&answer.option_id===option.id).length]))])):{};
      expenses.push({id:expense.id,title:expense.title,total:expense.total_cents/100,payer:uiName(expense.payer_person_id),payerMemberId:expense.payer_person_id,method:formula?'formula':expense.split_method,shares:Object.fromEntries(shareRows.results.map(s=>[uiName(s.person_id),s.amount_cents/100])),sharesByMemberId:Object.fromEntries(shareRows.results.map(s=>[s.person_id,s.amount_cents/100])),formula,myAnswers,answerCountsByQuestion,complete:formula?calculated.complete:true,incompleteReason:calculated?.reason||'',comment:expense.comment||'',date:new Date(expense.created_at.endsWith('Z')?expense.created_at:`${expense.created_at}Z`).toLocaleDateString('en-US',{month:'short',day:'numeric'}),icon:'🧾'});
    }
    output.push({id:group.id,name:group.name,icon:'✨',ownerUserId:group.owner_user_id,isLeader:group.owner_user_id===user.id,members:memberRecords.map(p=>p.isCurrentUser?'You':p.displayName),memberRecords,expenses,settlements:[]});
  }return output;
}

export async function handleBackend(request,env){
  const url=new URL(request.url),path=url.pathname;if(!path.startsWith('/api/')&&!path.startsWith('/auth/'))return null;
  try{
    requireDb(env);
    if(path==='/auth/login'){
      if(!env.GOOGLE_CLIENT_ID||!env.GOOGLE_CLIENT_SECRET)return new Response('Google OAuth secrets are not configured.',{status:503});
      const state=id(),google=new URL('https://accounts.google.com/o/oauth2/v2/auth');google.search=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,redirect_uri:`${url.origin}/auth/callback`,response_type:'code',scope:'openid email profile',state,prompt:'select_account'});
      const secure=url.protocol==='https:',headers=new Headers({location:google.toString()});headers.append('set-cookie',setCookie('split_circle_oauth_state',state,600,secure));headers.append('set-cookie',setCookie('split_circle_return_to',safeReturnTo(url.searchParams.get('returnTo')),600,secure));return new Response(null,{status:302,headers});
    }
    if(path==='/auth/judge'&&request.method==='POST'){
      if(!env.JUDGE_USERNAME||!env.JUDGE_PASSWORD)return json({error:'Judge access is not configured.'},503);
      let body;try{body=await request.json()}catch{return json({error:'Enter the judge username and password.'},400)}
      const username=typeof body.username==='string'?body.username.slice(0,100):'',password=typeof body.password==='string'?body.password.slice(0,200):'';
      const [usernameMatches,passwordMatches]=await Promise.all([secretEqual(username,env.JUDGE_USERNAME),secretEqual(password,env.JUDGE_PASSWORD)]);
      if(!usernameMatches||!passwordMatches)return json({error:'The judge credentials were not accepted.'},401);
      const existing=await env.DB.prepare('SELECT id FROM users WHERE google_sub=?').bind('judge-access').first(),userId=existing?.id||id(),displayName='Hackathon Judge',email='judge@split-circle.invalid';
      await env.DB.prepare(`INSERT INTO users(id,google_sub,email,display_name) VALUES(?,?,?,?) ON CONFLICT(google_sub) DO UPDATE SET display_name=excluded.display_name`).bind(userId,'judge-access',email,displayName).run();
      const person=await env.DB.prepare('SELECT id FROM people WHERE user_id=?').bind(userId).first();if(!person)await env.DB.prepare('INSERT INTO people(id,public_id,display_name,user_id) VALUES(?,?,?,?)').bind(id(),`#${id().replaceAll('-','').slice(0,8)}`,displayName,userId).run();
      const session=id(),expiry=new Date(Date.now()+12*36e5).toISOString();await env.DB.prepare('INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)').bind(session,userId,expiry).run();
      return new Response(JSON.stringify({ok:true}),{headers:{'content-type':'application/json; charset=UTF-8','set-cookie':setCookie('split_circle_session',session,12*3600,url.protocol==='https:')}});
    }
    if(path==='/auth/callback')return callback(request,env,url);
    if(path==='/auth/logout')return new Response(null,{status:302,headers:{location:'/','set-cookie':setCookie('split_circle_session','',0,url.protocol==='https:')}});
    if(path==='/api/me'){const user=await userFor(request,env);return json({user:user&&{id:user.id,name:user.display_name,email:user.email,personId:user.person_id,memberId:user.public_id}})}
    const user=await requireUser(request,env);
    if(path==='/api/groups'&&request.method==='GET')return json({groups:await serializeGroups(env,user)});
    if(path==='/api/member-search'){const q=(url.searchParams.get('q')||'').trim();if(q.length<2)return json({members:[]});const result=await env.DB.prepare(`SELECT DISTINCT p.id,p.public_id,p.display_name FROM people p JOIN group_members gm ON gm.person_id=p.id WHERE gm.group_id IN (SELECT gm2.group_id FROM group_members gm2 WHERE gm2.person_id=?) AND lower(p.display_name) LIKE ? ORDER BY p.display_name LIMIT 8`).bind(user.person_id,`%${q.toLowerCase()}%`).all();return json({members:result.results})}
    if(path==='/api/groups'&&request.method==='POST'){
      const body=await request.json();if(!body.name?.trim())return json({error:'Group name is required.'},400);const groupId=id();await env.DB.prepare('INSERT INTO groups(id,name,owner_user_id) VALUES(?,?,?)').bind(groupId,body.name.trim(),user.id).run();
      for(const member of [{personId:user.person_id},...(Array.isArray(body.members)?body.members:[])]){let personId=member.personId;if(!personId){const name=member.displayName?.trim();if(!name)continue;personId=id();await env.DB.prepare('INSERT INTO people(id,public_id,display_name) VALUES(?,?,?)').bind(personId,`#${id().replaceAll('-','').slice(0,8)}`,name).run()}await env.DB.prepare('INSERT OR IGNORE INTO group_members(group_id,person_id) VALUES(?,?)').bind(groupId,personId).run()}return json({id:groupId},201);
    }
    const memberRoute=path.match(/^\/api\/groups\/([^/]+)\/members$/);
    if(memberRoute&&request.method==='POST'){
      const group=await groupForUser(env,memberRoute[1],user);if(!group)return json({error:'Group was not found.'},404);
      const body=await request.json(),name=body.displayName?.trim();if(!name)return json({error:'Member name is required.'},400);
      let personId=body.personId;
      if(personId){const known=await env.DB.prepare(`SELECT p.id FROM people p JOIN group_members gm ON gm.person_id=p.id WHERE p.id=? AND gm.group_id IN (SELECT group_id FROM group_members WHERE person_id=?)`).bind(personId,user.person_id).first();if(!known)return json({error:'Choose a person you already share a group with.'},400)}
      else{personId=id();await env.DB.prepare('INSERT INTO people(id,public_id,display_name) VALUES(?,?,?)').bind(personId,`#${id().replaceAll('-','').slice(0,8)}`,name).run()}
      await env.DB.prepare('INSERT OR IGNORE INTO group_members(group_id,person_id) VALUES(?,?)').bind(group.id,personId).run();return json({personId},201);
    }
    const splitRoute=path.match(/^\/api\/groups\/([^/]+)\/splits$/);
    if(splitRoute&&request.method==='POST'){
      const group=await groupForUser(env,splitRoute[1],user);if(!group)return json({error:'Group was not found.'},404);const body=await request.json(),title=body.title?.trim(),totalCents=Math.round(Number(body.total)*100),method=body.splitMethod||'equal';
      if(!title||!Number.isSafeInteger(totalCents)||totalCents<=0)return json({error:'A title and positive total are required.'},400);if(!['equal','custom','formula'].includes(method))return json({error:'Split method must be equal, custom, or formula.'},400);
      const memberRows=await env.DB.prepare('SELECT person_id FROM group_members WHERE group_id=? ORDER BY person_id').bind(group.id).all(),memberIds=memberRows.results.map(r=>r.person_id);if(!memberIds.includes(body.paidByMemberId))return json({error:'The payer is not a member of this group.'},400);
      let shares,formula=null;if(method==='equal'){const included=Array.isArray(body.participantMemberIds)?body.participantMemberIds:memberIds;if(!included.length||new Set(included).size!==included.length||included.some(personId=>!memberIds.includes(personId)))return json({error:'Choose at least one unique group member for the split.'},400);const base=Math.floor(totalCents/included.length),remainder=totalCents%included.length;shares=memberIds.map(personId=>({personId,cents:included.includes(personId)?base+(included.indexOf(personId)<remainder?1:0):0}))}else if(method==='custom'){const supplied=body.sharesByMemberId||{};shares=memberIds.map(personId=>({personId,cents:Math.round(Number(supplied[personId]||0)*100)}));if(shares.some(s=>!Number.isSafeInteger(s.cents)||s.cents<0)||shares.reduce((sum,s)=>sum+s.cents,0)!==totalCents)return json({error:'Custom shares must use group member IDs and equal the total exactly.'},400)}else{try{formula=cleanFormula(body.formulaDefinition,totalCents,memberIds)}catch(error){return json({error:error.message},400)}shares=memberIds.map(personId=>({personId,cents:0}))}
      const expenseId=id(),statements=[env.DB.prepare(`INSERT INTO expenses(id,group_id,title,total_cents,payer_person_id,split_method,comment,formula_json,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?)`).bind(expenseId,group.id,title,totalCents,body.paidByMemberId,method==='formula'?'custom':method,String(body.comment||'').trim().slice(0,280)||null,formula?JSON.stringify(formula):null,user.id),...shares.map(s=>env.DB.prepare('INSERT INTO expense_shares(expense_id,person_id,amount_cents) VALUES(?,?,?)').bind(expenseId,s.personId,s.cents))];await env.DB.batch(statements);return json({id:expenseId,groupId:group.id,complete:!formula},201);
    }
    const answerRoute=path.match(/^\/api\/splits\/([^/]+)\/answers$/);
    if(answerRoute&&request.method==='POST'){
      const expense=await env.DB.prepare(`SELECT e.id,e.total_cents,e.formula_json,e.group_id FROM expenses e JOIN group_members gm ON gm.group_id=e.group_id WHERE e.id=? AND gm.person_id=?`).bind(answerRoute[1],user.person_id).first();if(!expense)return json({error:'Formula split was not found.'},404);if(!expense.formula_json)return json({error:'This split does not have questions.'},400);const formula=JSON.parse(expense.formula_json),body=await request.json(),question=formula.questions.find(question=>question.id===body.questionId);if(!formula.memberIds.includes(user.person_id))return json({error:'You are not a participant in this formula split.'},403);if(!question||!question.options.some(option=>option.id===body.optionId))return json({error:'Choose a valid question and option.'},400);
      await env.DB.prepare(`INSERT INTO expense_answers(expense_id,person_id,question_id,option_id) VALUES(?,?,?,?) ON CONFLICT(expense_id,person_id,question_id) DO UPDATE SET option_id=excluded.option_id`).bind(expense.id,user.person_id,question.id,body.optionId).run();const answers=await env.DB.prepare('SELECT person_id,question_id,option_id FROM expense_answers WHERE expense_id=?').bind(expense.id).all(),calculated=calculateFormulaShares(formula,answers.results,expense.total_cents),counts=Object.fromEntries(question.options.map(option=>[option.id,answers.results.filter(answer=>answer.question_id===question.id&&answer.option_id===option.id).length]));if(calculated.complete)await env.DB.batch(calculated.shares.map(share=>env.DB.prepare('UPDATE expense_shares SET amount_cents=? WHERE expense_id=? AND person_id=?').bind(share.cents,expense.id,share.personId)));return json({saved:true,complete:calculated.complete,counts,incompleteReason:calculated.reason||''});
    }
    const leaveRoute=path.match(/^\/api\/groups\/([^/]+)\/leave$/);if(leaveRoute&&request.method==='POST'){const membership=await groupForUser(env,leaveRoute[1],user);if(!membership)return json({error:'You are not a member of this group.'},404);const claimed=await env.DB.prepare(`SELECT COUNT(*) AS count FROM group_members gm JOIN people p ON p.id=gm.person_id WHERE gm.group_id=? AND p.user_id IS NOT NULL AND p.user_id<>?`).bind(leaveRoute[1],user.id).first();if(Number(claimed.count)===0){await env.DB.batch([env.DB.prepare('DELETE FROM group_share_links WHERE group_id=?').bind(leaveRoute[1]),env.DB.prepare('DELETE FROM invitations WHERE group_id=?').bind(leaveRoute[1]),env.DB.prepare('DELETE FROM expenses WHERE group_id=?').bind(leaveRoute[1]),env.DB.prepare('DELETE FROM group_members WHERE group_id=?').bind(leaveRoute[1]),env.DB.prepare('DELETE FROM groups WHERE id=?').bind(leaveRoute[1])]);return json({left:true,deleted:true})}await env.DB.prepare('DELETE FROM group_members WHERE group_id=? AND person_id=?').bind(leaveRoute[1],user.person_id).run();return json({left:true,deleted:false})}
    const shareRoute=path.match(/^\/api\/groups\/([^/]+)\/share-link$/);if(shareRoute&&request.method==='POST'){const owner=await env.DB.prepare('SELECT 1 FROM groups WHERE id=? AND owner_user_id=?').bind(shareRoute[1],user.id).first();if(!owner)return json({error:'Only the group leader can create a share link.'},403);const token=id().replaceAll('-',''),expiresAt=new Date(Date.now()+14*864e5).toISOString();await env.DB.prepare('INSERT INTO group_share_links(token,group_id,created_by_user_id,expires_at) VALUES(?,?,?,?)').bind(token,shareRoute[1],user.id,expiresAt).run();return json({url:`${url.origin}/join/${token}`,expiresAt},201)}
    const joinRoute=path.match(/^\/api\/group-share-links\/([^/]+)$/);if(joinRoute&&request.method==='GET'){const link=await env.DB.prepare(`SELECT group_id FROM group_share_links WHERE token=? AND revoked_at IS NULL AND expires_at>CURRENT_TIMESTAMP`).bind(joinRoute[1]).first();if(!link)return json({error:'This share link is unavailable.'},404);const group=await env.DB.prepare('SELECT name FROM groups WHERE id=?').bind(link.group_id).first(),people=await env.DB.prepare(`SELECT p.id,p.display_name,p.public_id FROM people p JOIN group_members gm ON gm.person_id=p.id WHERE gm.group_id=? AND p.user_id IS NULL ORDER BY p.display_name`).bind(link.group_id).all(),membership=await groupForUser(env,link.group_id,user);return json({group:{id:link.group_id,name:group.name},isMember:Boolean(membership),unclaimedMembers:people.results})}
    const joinClaim=path.match(/^\/api\/group-share-links\/([^/]+)\/claim$/);if(joinClaim&&request.method==='POST'){const body=await request.json(),link=await env.DB.prepare(`SELECT group_id FROM group_share_links WHERE token=? AND revoked_at IS NULL AND expires_at>CURRENT_TIMESTAMP`).bind(joinClaim[1]).first();if(!link)return json({error:'This share link is unavailable.'},404);const member=await env.DB.prepare(`SELECT p.id FROM people p JOIN group_members gm ON gm.person_id=p.id WHERE gm.group_id=? AND p.id=? AND p.user_id IS NULL`).bind(link.group_id,body.personId).first();if(!member)return json({error:'That name has already been claimed or is not in this group.'},409);const own=await env.DB.prepare('SELECT id FROM people WHERE user_id=?').bind(user.id).first();if(own&&own.id!==member.id){await env.DB.batch([env.DB.prepare(`UPDATE expense_shares SET person_id=? WHERE person_id=? AND expense_id IN (SELECT id FROM expenses WHERE group_id=?)`).bind(own.id,member.id,link.group_id),env.DB.prepare('UPDATE expenses SET payer_person_id=? WHERE payer_person_id=? AND group_id=?').bind(own.id,member.id,link.group_id),env.DB.prepare('UPDATE invitations SET person_id=? WHERE person_id=? AND group_id=?').bind(own.id,member.id,link.group_id),env.DB.prepare('UPDATE group_members SET person_id=? WHERE group_id=? AND person_id=?').bind(own.id,link.group_id,member.id),env.DB.prepare('DELETE FROM people WHERE id=? AND user_id IS NULL').bind(member.id)])}else await env.DB.prepare('UPDATE people SET user_id=? WHERE id=? AND user_id IS NULL').bind(user.id,member.id).run();return json({claimed:true,groupId:link.group_id})}
    return json({error:'Not found'},404);
  }catch(error){if(error instanceof Response)return error;return json({error:error.message||'Unexpected server error'},500)}
}
